project:
  type: website

website:
  title: "My Explorations with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/i%C3%B1igo-herrero-382806305/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


